from core.domain.entities.couse_subject import CourseSubject
from core.domain.repositories.course_subject_repository import CourseSubjectRepository
from rest_framework.exceptions import ValidationError, NotFound

class CreateCourseSubjectService:
    def __init__(self, course_subject_repository:CourseSubjectRepository):
        self.course_subject_repository = course_subject_repository

    def execute(self, courseId, subjectId, hoursPerWeek, isRequired):

        course_subject = CourseSubject(
            id=None,  # Assuming ID is auto-generated by the repository
            courseId=courseId,
            subjectId=subjectId,
            hoursPerWeek=hoursPerWeek,
            isRequired=isRequired
        )
        if self.course_subject_repository.exist_by_course_and_subject(courseId, subjectId):
            raise ValidationError("CourseSubject with this course and subject already exists")
        return self.course_subject_repository.create(course_subject)
