# Generated by Django 5.2 on 2025-04-27 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LevelModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField()),
            ],
            options={
                "verbose_name": "Level",
                "db_table": "level",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LogActivityModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userId", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log Activity",
                "db_table": "log_activity",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SchoolYearModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("planning", "Planning"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="planning",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "School Year",
                "db_table": "school_year",
                "ordering": ["startDate"],
            },
        ),
        migrations.CreateModel(
            name="SectionModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                            ("weekend", "Weekend"),
                        ],
                        default="morning",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Section",
                "db_table": "section",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubjectModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("hoursPerWeek", models.IntegerField()),
            ],
            options={
                "verbose_name": "Subject",
                "db_table": "subject",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CourseModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="core.levelmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "db_table": "course",
            },
        ),
        migrations.CreateModel(
            name="ParallelModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("capacity", models.IntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parallels",
                        to="core.coursemodel",
                    ),
                ),
                (
                    "schoolYear",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parallels",
                        to="core.schoolyearmodel",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parallels",
                        to="core.sectionmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parallel",
                "verbose_name_plural": "Parallels",
                "db_table": "parallel",
                "ordering": ["name"],
                "unique_together": {("name", "course", "section", "schoolYear")},
            },
        ),
        migrations.CreateModel(
            name="CourseSubjectModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hoursPerWeek", models.IntegerField()),
                ("isRequired", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_subjects",
                        to="core.coursemodel",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_subjects",
                        to="core.subjectmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Subject",
                "db_table": "course_subject",
                "unique_together": {("course", "subject")},
            },
        ),
    ]
