# Generated by Django 5.2 on 2025-05-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursesubjectmodel",
            name="hoursPerWeek",
        ),
    ]
