# Generated by Django 5.2 on 2025-05-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_coursesubjectmodel_hoursperweek"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Configuration",
                "db_table": "configuration",
                "ordering": ["key"],
            },
        ),
        migrations.AlterField(
            model_name="schoolyearmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("planning", "Planning"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                ],
                default="planning",
                max_length=255,
            ),
        ),
    ]
