# Generated by Django 5.2 on 2025-06-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_configurationmodel_alter_schoolyearmodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionmodel",
            name="breakCount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sectionmodel",
            name="breakDuration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sectionmodel",
            name="days",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sectionmodel",
            name="endDate",
            field=models.TimeField(default="17:00:00"),
        ),
        migrations.AddField(
            model_name="sectionmodel",
            name="hasBreak",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sectionmodel",
            name="startDate",
            field=models.TimeField(default="08:00:00"),
        ),
    ]
