# Generated by Django 5.2 on 2025-08-07 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_attendancecodemodel_behaviorscalemodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicPlanningModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=255)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_plannings",
                        to="core.coursemodel",
                    ),
                ),
                (
                    "parallel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_plannings",
                        to="core.parallelmodel",
                    ),
                ),
                (
                    "schoolYear",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_plannings",
                        to="core.schoolyearmodel",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_plannings",
                        to="core.subjectmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Planning",
                "verbose_name_plural": "Academic Plannings",
                "db_table": "academic_planning",
                "ordering": ["startDate"],
                "unique_together": {("parallel", "subject", "startDate")},
            },
        ),
    ]
