# Generated by Django 5.2 on 2025-08-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_academicplanningmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parallelmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
