# Generated by Django 5.2 on 2025-08-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_parallelmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmodel',
            name='class_duration',
            field=models.TimeField(default='00:45:00'),
        ),
    ]
