# Generated by Django 5.2 on 2025-08-30 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sectionmodel_class_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionBreakModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='core.sectionmodel')),
            ],
            options={
                'verbose_name': 'Section Break',
                'verbose_name_plural': 'Section Breaks',
                'db_table': 'section_break',
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
