

from core.domain.entities.section import Section
from core.domain.repositories.section_repository import SectionRepository
from rest_framework.exceptions import ValidationError, ErrorDetail

class CreateSectionService:
    def __init__(self, section_repository:SectionRepository):
        self.section_repository = section_repository
        
    def execute(self, name: str, type:str, description:str):
        # Validate the section data
        if  self.section_repository.exist_by_name(name):
            raise ValidationError("Section name is required.", code=ErrorDetail(string="name", code="required"))
        
        
        # Create a new section object
        new_section = Section(
            id=None,  # Assuming ID is auto-generated by the repository
            name=name,
            type=type,
            description=description
        )
        
        new_section = self.section_repository.create(new_section)
        return new_section