


from core.domain.entities.school_year import SchoolYear
from core.domain.repositories.school_year_repository import SchoolYearRepository
from rest_framework.exceptions import ValidationError, ErrorDetail

class CreateSchoolYearService:
    
    def __init__(self, school_year_repository: SchoolYearRepository ):
        self.school_year_repository = school_year_repository
        

    def execute(self, name: str, startDate: str, endDate: str, status: str):
        
        if self.school_year_repository.exist_by_name(name):
            raise ValidationError("School year with this name already exists.", code=ErrorDetail(string="name", code="unique"))
        
        new_school_year = SchoolYear(
            id=None,  # Assuming ID is auto-generated by the repository
            name=name,
            startDate=startDate,
            endDate=endDate,
            status=status
        )
        
        return self.school_year_repository.create(new_school_year)
